import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/components/providers/theme-provider";
import Link from "next/link";
import { cn } from "@/lib/utils";
import { ModalProvider } from "@/components/providers/modal-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Discord Clone",
  description: "Generated by Nadim Chowdhury",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body
          className={cn(
            inter.className,
            "relative bg-white dark:bg-neutral-900"
          )}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            // forcedTheme="dark"
            enableSystem
            // disableTransitionOnChange
            storageKey="discord-theme"
          >
            {/* <ModalProvider /> */}
            {children}
          </ThemeProvider>

          {/* <Link
            href="https://nadim.vercel.app"
            className="bottom-0 right-0 text-teal-500"
          >
            &copy; Nadim Chowdhury
          </Link> */}
        </body>
      </html>
    </ClerkProvider>
  );
}
